#!/usr/bin/env python3
"""CS 218 Lab 2 workload.

This one file runs, unchanged, in your container and in your virtual machine. That is
what makes the comparison fair: same program, same Python, same work, and the only thing
that differs is what sits underneath it.

It does three things:

  * holds a fixed working set in memory (WORKSET_MB, default 64), so there is a known
    amount of "tenant memory" to subtract when you measure overhead;
  * does a fixed amount of CPU work per request on /work, so latency under a noisy
    neighbour is comparable between runs;
  * reports on /probe what the machine looks like from inside: which kernel, how much
    memory and how many CPUs it thinks it has, who it is, and what limits it is under.

Standard library only. Do not edit this file: lab.py checks that the copy in your
container and the copy in your VM are byte-identical to this one.
"""

import hashlib
import json
import os
import platform
import signal
import socket
import sys
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

VERSION = "2026.09.1"
PORT = int(os.environ.get("PORT", "8080"))
WORKSET_MB = int(os.environ.get("WORKSET_MB", "64"))
WORK_ROUNDS = int(os.environ.get("WORK_ROUNDS", "200"))
BLOCK = b"\x5a" * 65536  # 64 KiB; /work hashes it WORK_ROUNDS times, about 12.5 MiB

with open(os.path.abspath(__file__), "rb") as _f:
    SOURCE_SHA256 = hashlib.sha256(_f.read()).hexdigest()

STARTED_AT = time.time()
READY = {}


def _read(path, default=None):
    try:
        with open(path) as f:
            return f.read().strip()
    except OSError:
        return default


def _status_fields(*names):
    out = {}
    for line in (_read("/proc/self/status") or "").splitlines():
        key, _, value = line.partition(":")
        if key in names:
            out[key] = value.strip()
    return out


def _meminfo():
    wanted = ("MemTotal", "MemFree", "MemAvailable", "Buffers", "Cached", "Shmem",
              "Slab", "SReclaimable", "SUnreclaim", "KernelStack", "PageTables")
    out = {}
    for line in (_read("/proc/meminfo") or "").splitlines():
        key, _, value = line.partition(":")
        if key in wanted:
            out[key + "_kB"] = int(value.split()[0])
    return out


def _cgroup_dir():
    # cgroup v2: the line "0::/some/path" names this process's group.
    for line in (_read("/proc/self/cgroup") or "").splitlines():
        if line.startswith("0::"):
            return "/sys/fs/cgroup" + line[3:].rstrip("/")
    return None


def _cgroup():
    d = _cgroup_dir()
    if not d:
        return {"version": "v1 or none"}
    return {
        "path": d,
        "memory.max": _read(d + "/memory.max"),
        "memory.current": _read(d + "/memory.current"),
        "cpu.max": _read(d + "/cpu.max"),
        "pids.max": _read(d + "/pids.max"),
        "pids.current": _read(d + "/pids.current"),
    }


def _capability_count(hex_mask):
    try:
        return bin(int(hex_mask, 16)).count("1")
    except (TypeError, ValueError):
        return None


def _process_age_seconds():
    # Field 22 of /proc/self/stat is the start time in clock ticks since boot. Measured
    # against /proc/uptime it gives how long this process has existed, interpreter
    # start-up included.
    stat = _read("/proc/self/stat")
    uptime = _read("/proc/uptime")
    if not stat or not uptime:
        return None
    fields = stat.rsplit(")", 1)[1].split()
    start_ticks = int(fields[19])
    return round(float(uptime.split()[0]) - start_ticks / os.sysconf("SC_CLK_TCK"), 3)


def _os_release():
    for line in (_read("/etc/os-release") or "").splitlines():
        if line.startswith("PRETTY_NAME="):
            return line.split("=", 1)[1].strip('"')
    return None


def _virtualization():
    cpuinfo = _read("/proc/cpuinfo") or ""
    return {
        "cpu_hypervisor_flag": " hypervisor" in cpuinfo,
        "dmi_sys_vendor": _read("/sys/class/dmi/id/sys_vendor"),
        "dmi_product_name": _read("/sys/class/dmi/id/product_name"),
        "device_tree_model": (_read("/proc/device-tree/model") or "").strip("\x00") or None,
        "dockerenv_file": os.path.exists("/.dockerenv"),
        "containerenv_file": os.path.exists("/run/.containerenv"),
        "lab2_vm_marker": os.path.exists("/etc/cs218-lab2-vm"),
    }


def _namespaces():
    out = {}
    for name in ("cgroup", "ipc", "mnt", "net", "pid", "time", "user", "uts"):
        try:
            out[name] = os.readlink("/proc/self/ns/" + name)
        except OSError:
            out[name] = None
    return out


def probe():
    status = _status_fields("VmRSS", "VmHWM", "RssAnon", "RssFile", "CapEff", "CapBnd", "Seccomp",
                           "NoNewPrivs")
    try:
        affinity = len(os.sched_getaffinity(0))
    except (AttributeError, OSError):
        affinity = None
    uptime = _read("/proc/uptime")
    return {
        "app": {
            "version": VERSION,
            "source_sha256": SOURCE_SHA256,
            "python": platform.python_version(),
            "pid": os.getpid(),
            "workset_mb": WORKSET_MB,
            "work_rounds": WORK_ROUNDS,
            "ready": READY,
        },
        "kernel": {
            "release": platform.release(),
            "machine": platform.machine(),
            "boot_id": _read("/proc/sys/kernel/random/boot_id"),
            "uptime_s": float(uptime.split()[0]) if uptime else None,
        },
        "os_release": _os_release(),
        "hostname": socket.gethostname(),
        "virtualization": _virtualization(),
        "cpu": {"os_cpu_count": os.cpu_count(), "affinity": affinity},
        "memory": dict(_meminfo(), self_VmRSS=status.get("VmRSS"), self_VmHWM=status.get("VmHWM"),
                       self_RssAnon=status.get("RssAnon"), self_RssFile=status.get("RssFile")),
        "cgroup": _cgroup(),
        "identity": {
            "uid": os.getuid(),
            "gid": os.getgid(),
            "uid_map": " ".join((_read("/proc/self/uid_map") or "").split()),
            "cap_effective": status.get("CapEff"),
            "cap_bounding": status.get("CapBnd"),
            "cap_bounding_count": _capability_count(status.get("CapBnd")),
            "seccomp_mode": status.get("Seccomp"),
            "no_new_privs": status.get("NoNewPrivs"),
        },
        "processes": {
            "visible": sum(1 for p in os.listdir("/proc") if p.isdigit()) if os.path.isdir("/proc") else None,
            "pid1_comm": _read("/proc/1/comm"),
        },
        "namespaces": _namespaces(),
    }


def work():
    t0 = time.perf_counter()
    h = hashlib.sha256()
    for _ in range(WORK_ROUNDS):
        h.update(BLOCK)
    return {"digest": h.hexdigest()[:16], "server_ms": round((time.perf_counter() - t0) * 1000, 3)}


class Handler(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"
    # Headers and body go out in separate writes. With Nagle's algorithm on, the second
    # write waits for the client to acknowledge the first, and a client that delays its
    # ACKs adds tens of milliseconds to every request on a reused connection.
    disable_nagle_algorithm = True

    def _send(self, code, payload):
        body = json.dumps(payload, indent=1).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        path = self.path.split("?", 1)[0]
        if path == "/health":
            self._send(200, {"ok": True, "boot_id": _read("/proc/sys/kernel/random/boot_id")})
        elif path == "/work":
            self._send(200, work())
        elif path == "/probe":
            self._send(200, probe())
        else:
            self._send(404, {"error": "try /health, /work or /probe"})

    def log_message(self, fmt, *args):
        pass  # one line per request would drown the useful output


def main():
    # The working set: allocate it, then write one byte per 4 KiB page so every page is
    # really resident rather than a promise the kernel has not kept yet.
    workset = bytearray(WORKSET_MB * 1024 * 1024)
    for i in range(0, len(workset), 4096):
        workset[i] = 1

    server = ThreadingHTTPServer(("0.0.0.0", PORT), Handler)

    # `docker stop` and systemd both ask politely first, with SIGTERM. A process that is
    # PID 1 gets no default handler for it, so without this line the request is ignored
    # and the stop waits out its whole grace period before resorting to SIGKILL.
    signal.signal(signal.SIGTERM, lambda signum, frame: sys.exit(0))

    uptime = _read("/proc/uptime")
    READY.update({
        "process_age_at_ready_s": _process_age_seconds(),
        "kernel_uptime_at_ready_s": float(uptime.split()[0]) if uptime else None,
    })
    print(f"lab2 app {VERSION} listening on :{PORT}, working set {WORKSET_MB} MB, "
          f"python {platform.python_version()}", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        del workset


if __name__ == "__main__":
    sys.exit(main())
